### ISSUE TITLE
cdnjs.cloudflare.com is blocked in China

### ISSUE THREAD

**Issue by imchenxi** [ShareDropio/sharedrop#22]
Thanks for creating such a good web tool for sharing!

But the web site cannot be opened in China because files hosted in cdnjs.cloudflare.com (like: jquery.min.js, handlebars.runtime.min.js and ember.min.js) are blocked by the [GFW](https://en.wikipedia.org/wiki/Great_Firewall_of_China) (Great Firewall, a nick name of the internet censorship project in China). 

So could you please host these files in another CDN? such as Google?

BTW, a URL can be tested in [this site](https://en.greatfire.org/) to see if it is blocked in China.

**Comment by PeterDaveHello** [comment]
There should be no problem now. https://www.cloudflare.com/china
